config/routes.rb
Track::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :issues, path: '/', only: [:show, :new, :create, :update] do
    collection do
      get 'issues/:scope', action: :index, as: :scoped
      post :search
    end
  end

  root to: 'issues#new'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name, :ref_code
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :body, :department_id, :email, :name, :subject

  belongs_to :department
  belongs_to :user

  has_many :replies

  validates :ref, :name, :email, :subject, :body, :department, :state, presence: true
  validates :ref, :uniqueness => true

  validates_email_format_of :email

  before_validation :set_reference_number

  state_machine :state, :initial => :waiting_for_staff_response do

    event :updated_by_staff do
      transition any - [:cancelled, :completed] => :waiting_for_customer
    end

    event :updated_by_customer do
      transition any - [:cancelled, :completed] => :waiting_for_staff_response
    end

    event :suspend do
      transition [:waiting_for_staff_response, :waiting_for_customer] => :on_hold
    end

    event :cancel do
      transition any - [:cancelled, :completed] => :cancelled
    end

    event :resolve do
      transition any - [:cancelled, :completed] => :completed
    end

    state :waiting_for_staff_response, :waiting_for_customer, :on_hold do
      def closed?
        false
      end
    end

    state :cancelled, :completed do
      def closed?
        true
      end
    end

  end

  scope :unassigned, where(:user_id => nil).with_states(:waiting_for_staff_response)
  scope :open, with_states(:waiting_for_staff_response, :waiting_for_customer)
  scope :on_hold, with_states(:on_hold)
  scope :closed, with_states(:cancelled, :completed)

  def self.states
    self.state_machines[:state].states.map &:name
  end

  def add_reply( message, replying_user = nil, event = :update, assigned_user = nil )
    reply = replies.new( body: message, user: replying_user )
    starting_state = state

    # Update the issue's assigned user if required
    if assigned_user.present? and assigned_user != self.user
      reply.assigned_user = assigned_user
      self.user = assigned_user
    end

    # Carry out any events
    case event
    when :suspend
      suspend!
    when :cancel
      cancel!
    when :resolve
      resolve!
    else
      if replying_user.nil?
        updated_by_customer!
      elsif !message.empty?
        updated_by_staff!
      end
    end

    if starting_state != state
      reply.state_change = human_state_name
    end

    reply.save!

    return reply
  end

  def user_id
    user.id unless user.nil?
  end

  def to_param
    ref
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['ref LIKE ? OR body LIKE ?',"%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end

private

  def set_reference_number
    if ref.nil? and department.present?
      self.ref = loop do
        ref_code = generate_ref
        break ref_code unless self.class.where(ref: ref_code).exists?
      end
    end
  end

  def generate_ref
    "#{department.ref_code}-#{sprintf( '%06d', SecureRandom.random_number(999999) )}"
  end

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :assigned_user_id, :body, :issue_id, :state_change, :user_id, :user

  belongs_to :issue
  belongs_to :user
  belongs_to :assigned_user, class_name: 'User'

  def display_user
    user.present? ? user.email : 'Customer'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :verify_user_auth, except: [:show, :new, :create, :update]

  def show
    @issue = Issue.find_by_ref(params[:id])
    @users = User.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        IssueMailer.new_issue(@issue).deliver

        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    event = params[:commit].parameterize.downcase.to_sym
    assigned_user = User.find_by_id(params[:assigned_user_id])

    @issue = Issue.find_by_ref(params[:id])
    @reply = @issue.add_reply( params[:message], current_user, event, assigned_user )

    # Send user any updates made by staff
    if current_user
      IssueMailer.updated_issue(@issue, @reply).deliver
    end

    respond_to do |format|
      format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
      format.json { head :no_content }
    end

  end

  def index
    @issues = Issue.send params[:scope].to_sym

    respond_to do |format|
      format.html # unassigned.html.erb
      format.json { render json: @issues }
    end
  end

  def search
    @term = params[:s] || ""
    @issues = Issue.search @term
  end

private

  def verify_user_auth
    redirect_to root_path, :flash => { :error => "Unauthorized!" } unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.haml
= form_for @issue, :validate => true, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :department, :class => 'control-label'
    .controls
      = f.collection_select :department_id, Department.all, :id, :name, :prompt => true
  .control-group
    = f.label :subject, :class => 'control-label'
    .controls
      = f.text_field :subject, :class => 'text_field'
  .control-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_area :body, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), issues_path, :class => 'btn'

app/views/issues/_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= Issue.human_attribute_name(:ref)
      %th= Issue.human_attribute_name(:subject)
      %th= Issue.human_attribute_name(:state)
      %th= Issue.human_attribute_name(:name)
      %th= Issue.human_attribute_name(:email)
      %th= Issue.human_attribute_name(:created)
  %tbody
    - @issues.each do |issue|
      %tr
        %td= link_to issue.ref, issue_path(issue)
        %td= issue.subject
        %td= issue.human_state_name
        %td= issue.name
        %td= issue.email
        %td= "#{time_ago_in_words issue.created_at} ago"

app/views/issues/edit.html.haml
- model_class = Issue
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/issues/index.html.haml
.page-header
  %h1= "Issues: #{params[:scope].humanize.capitalize}"
  = render partial: 'table'

app/views/issues/new.html.haml
.page-header
  %h1 Submit Issue
= render :partial => "form"

app/views/issues/search.html.haml
.page-header
  %h1= "Search: #{@term}"
  = render partial: 'table'

app/views/issues/show.html.haml
.page-header
  %h1= "Issue: #{@issue.ref}"
  %h4= "Assigned to #{@issue.user.email}" if @issue.user.present?

%p
  %strong= Issue.human_attribute_name(:state) + ':'
  %br
  = @issue.human_state_name
%p
  %strong= Issue.human_attribute_name(:name) + ':'
  %br
  = @issue.name
%p
  %strong= Issue.human_attribute_name(:email) + ':'
  %br
  = @issue.email
%p
  %strong= Issue.human_attribute_name(:department) + ':'
  %br
  = @issue.department.name
%p
  %strong= Issue.human_attribute_name(:subject) + ':'
  %br
  = @issue.subject
%p
  %strong= Issue.human_attribute_name(:created) + ':'
  %br
  = "#{time_ago_in_words @issue.created_at} ago"
.well
  %p.lead
    = @issue.body

- unless @issue.replies.empty?
  .page-header
    %h4= "Replies"

  - @issue.replies.each do | reply |
    - unless reply.body.empty?
      .well
        %p.muted
          = reply.display_user
          updated
          = time_ago_in_words reply.created_at
          ago:
        %p.lead= reply.body

    - if reply.assigned_user.present?
      .well
        %p.muted
          = reply.display_user
          updated
          = time_ago_in_words reply.created_at
          ago:
        %p
          %i.icon-hand-right
          Issue assigned to:
          %strong= reply.assigned_user.email


    - if reply.state_change.present?
      .well
        %p.muted
          = reply.display_user
          updated
          = time_ago_in_words reply.created_at
          ago:
        %p
          %i.icon-warning-sign
          Status changed to:
          %strong= reply.state_change

- unless @issue.closed?
  .page-header
    %h4= "Update Issue"

  = form_tag issue_path(@issue), :method => :put, :class => 'form-horizontal' do
    - if user_signed_in?
      .control-group
        = label_tag :assign_to, nil, :class => 'control-label'
        .controls
          = select_tag :assigned_user_id, options_from_collection_for_select(@users, "id", "email", @issue.user_id), :prompt => 'Assign to...', :class => 'text_field'
    .control-group
      = label_tag :reply, nil, :class => 'control-label'
      .controls
        = text_area_tag :message, nil, :class => 'text_field'
    .form-actions
      = submit_tag 'Update', :class => 'btn btn-primary'
      = submit_tag 'Suspend', :class => 'btn btn-inverse' unless @issue.on_hold?
      = submit_tag 'Cancel', :class => 'btn btn-primary btn-danger'
      = submit_tag 'Resolve', :class => 'btn btn-success'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "CustomerHandler"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") CustomerHandler
          .container.nav-collapse
            %ul.nav
              - if user_signed_in?
                %li= link_to current_user.email, '#'
                %li= link_to "Log Out", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Support Staff Login", new_user_session_path

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Menu
              %li= link_to "New Issue", root_path
              - if user_signed_in?
                %li.nav-header Staff Menu
                - [:unassigned, :open, :on_hold, :closed].each do | scope |
                  %li= link_to scope.to_s.humanize.capitalize, scoped_issues_path(scope)

          - if user_signed_in?
            .well.sidebar-nav
              = form_tag search_issues_path do |f|
                = text_field_tag :s, params[:s]
                = submit_tag "Search", :name => nil

        .span9
          = bootstrap_flash
          = yield

      %footer
        %p &copy; host-tastic 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"